/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/csrf-cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["csrf-cookie"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated because every list in this application is. The global scope and
         *     the database policy both restrict it to the current tenant; neither is
         *     mentioned here, which is the point of putting them where they are
         */
        get: operations["api-keys.index"];
        put?: never;
        post: operations["api-keys.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys/{apiKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * A key from another tenant does not reach this method: the route binding
         *     resolves it through the tenant scope, so the answer is 404 rather than 403.
         *     Whether a key exists elsewhere is not this tenant's business
         */
        delete: operations["api-keys.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["applications.index"];
        put?: never;
        post: operations["applications.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/applications/{application}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A foreign tenant's application never reaches this method: route model
         *     binding resolves it through the tenant scope, so the answer is 404
         *     rather than 403
         */
        get: operations["applications.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["applications.update"];
        trace?: never;
    };
    "/v1/applications/{application}/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nested under the application whose endpoints these are; a foreign
         *     tenant's application is already a 404 by the time this runs
         */
        get: operations["applications.endpoints.index"];
        put?: never;
        post: operations["applications.endpoints.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/endpoints/{endpoint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["endpoints.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["endpoints.update"];
        trace?: never;
    };
    "/v1/endpoints/{endpoint}/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["endpoints.subscriptions.sync"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/endpoints/{endpoint}/test-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * D76: the ordinary ingest path, narrowed to this one endpoint and
         *     marked — not a second delivery mechanism. governor still applies
         *     (routes/api.php), so this costs the tenant a rate-limit token and a
         *     quota unit exactly like a producer's own publish
         */
        post: operations["endpoints.test-events.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/endpoints/{endpoint}/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["endpoints.secrets.index"];
        put?: never;
        /**
         * Issuing is how an endpoint rotates (App\Actions\Catalog\IssueEndpointSecret's
         *     own docblock) — there is no separate rotate endpoint
         */
        post: operations["endpoints.secrets.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/endpoints/{endpoint}/secrets/{secret}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * A secret from another endpoint — even one in the same tenant — is a
         *     404 here: the route names an endpoint and a secret together, and a
         *     secret that does not belong to that endpoint is not this route's
         *     resource, the same "a foreign id is 404, not 403" reasoning route
         *     model binding already applies across tenants
         */
        delete: operations["endpoints.secrets.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["event-types.index"];
        put?: never;
        post: operations["event-types.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/apps/{application}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The application is resolved through the tenant scope by route model
         *     binding, so one belonging to another tenant is answered with 404 and never
         *     reaches this method
         * @description A replay answers 200 rather than 201, with a header saying so: the body is
         *     the original message, byte for byte, and nothing was created to produce it.
         */
        post: operations["messages.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages/{message}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The message is resolved through the tenant scope by route model
         *     binding, so one belonging to another tenant is answered with 404 and
         *     never reaches this method — the same guarantee MessageController's own
         *     {application} parameter carries
         */
        post: operations["replays.message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/endpoints/{endpoint}/replays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bounded and paginated: at most postbox.replay.max_deliveries_per_request
         *     exhausted deliveries per call, with next_cursor carrying the rest — an
         *     operator recovering a large outage calls this again with that cursor
         *     rather than this action holding one transaction open for the whole
         *     window
         */
        post: operations["replays.range"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiKeyResource */
        ApiKeyResource: {
            id: string;
            name: string;
            last_four: string;
            last_used_at: string;
            expires_at: string;
            revoked_at: string;
            created_at: string;
        };
        /** ApplicationResource */
        ApplicationResource: {
            id: string;
            name: string;
            endpoint_count: string;
            created_at: string;
        };
        /** EndpointResource */
        EndpointResource: {
            id: string;
            application_id: string;
            name: string;
            url: string;
            status: string;
            subscriptions: string[];
            breaker: {
                state: string;
                state_changed_at: string;
            } | null;
            active_secret_count: number;
            created_at: string;
        };
        /** EndpointSecretResource */
        EndpointSecretResource: {
            id: string;
            last_four: string;
            expires_at: string;
            revoked_at: string;
            created_at: string;
        };
        /** EventTypeResource */
        EventTypeResource: {
            name: string;
            subscriber_count: string;
            created_at: string;
        };
        /** HealthResource */
        HealthResource: {
            status: string;
            checked_at: string;
            duration_ms: number;
            checks: unknown[];
        };
        /** IdentityResource */
        IdentityResource: {
            user: {
                id: string;
                name: string;
                email: string;
            };
            tenant: {
                id: string;
                name: string;
            };
            /**
             * @description The client renders from this list rather than from a role name, for
             *     the same reason the policies read it: the mapping from role to
             *     permission is data and may change without the client changing.
             */
            permissions: string[];
        };
        /** IssuedApiKeyResource */
        IssuedApiKeyResource: {
            id: string;
            name: string;
            last_four: string;
            last_used_at: string;
            expires_at: string;
            revoked_at: string;
            created_at: string;
            /**
             * @description Shown once. It is not stored in this shape anywhere, so a client
             *     that loses it here has to create another key.
             */
            token: string;
        };
        /** IssuedEndpointSecretResource */
        IssuedEndpointSecretResource: {
            id: string;
            last_four: string;
            expires_at: string;
            revoked_at: string;
            created_at: string;
            /**
             * @description Shown once. A client that loses it here has to issue
             *     another secret — the row can decrypt its own value again,
             *     but nothing in this API will ever hand it back out.
             */
            secret: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** MessageResource */
        MessageResource: {
            id: string;
            event_type: string;
            source: string;
            created_at: string;
        };
        /**
         * PublishMessageRequest
         * @description There is no authorize() here, and the omission is deliberate. A policy answers
         *     "may this actor do this to this resource", and the ingest surface has no actor:
         *     an API key produces a tenant, not a person. What stands in for authorization is
         *     the tenant boundary itself — the application in the route resolves through the
         *     tenant scope, so another tenant's application is a 404 before this class is
         *     ever constructed, and the event type below is only findable within the tenant
         *     for the same reason.
         */
        PublishMessageRequest: {
            /**
             * @description An event type is registered before it can be published, rather than
             *     created here: a typo would otherwise become a permanent event type
             *     that no endpoint is subscribed to, and the message would be accepted
             *     and delivered nowhere. The lookup needs no tenant predicate of its
             *     own — the application connects as a role Row Level Security applies
             *     to, so it can only ever match a row in the current tenant.
             */
            event_type: string;
            payload: string[];
        };
        /** ReplayMessageRequest */
        ReplayMessageRequest: {
            /**
             * @description Narrows the replay to one of the message's original
             *     subscribers. Absent, every endpoint the message's own fan-out
             *     reached is replayed. The lookup needs no tenant predicate of
             *     its own, the same reason PublishMessageRequest's event_type
             *     rule needs none: the application connects as a role Row Level
             *     Security applies to, so it can only ever match this tenant's
             *     own endpoint.
             */
            endpoint?: string | null;
        };
        /** ReplayRangeRequest */
        ReplayRangeRequest: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /**
             * @description Opaque; a caller only ever carries one back from a previous
             *     response, never composes one by hand.
             */
            cursor?: string | null;
        };
        /** ReplayResource */
        ReplayResource: {
            /** @description The replay receipt, rpl_... */
            id: string;
            /** @description Set for a single-message replay. */
            message_id: string | null;
            /** @description Set for a single-message replay to one endpoint, or a range replay. */
            endpoint_id: string | null;
            /**
             * Format: date-time
             * @description Set for a range replay.
             */
            range_from: string | null;
            /**
             * Format: date-time
             * @description Set for a range replay.
             */
            range_to: string | null;
            delivery_count: number;
            /** Format: date-time */
            created_at: string;
            /** @description Present only for a range replay — absent (not null) for a single message, since pagination never applied to it in the first place. */
            next_cursor?: string | null;
        };
        /** SendTestEventRequest */
        SendTestEventRequest: {
            event_type: string;
        };
        /** StoreApiKeyRequest */
        StoreApiKeyRequest: {
            name: string;
            /**
             * Format: date-time
             * @description Optional, because most keys are meant to outlive the person who
             *     created them; bounded when given, because a key that expires in the
             *     past is a support ticket rather than a credential.
             */
            expires_at?: string | null;
        };
        /** StoreApplicationRequest */
        StoreApplicationRequest: {
            /**
             * @description Scoped to the current tenant by Row Level Security, the same
             *     way PublishMessageRequest's event_type check needs no explicit
             *     tenant predicate of its own.
             */
            name: string;
        };
        /** StoreEndpointRequest */
        StoreEndpointRequest: {
            name: string;
            /** Format: uri */
            url: string;
        };
        /** StoreEventTypeRequest */
        StoreEventTypeRequest: {
            /**
             * @description Same shape the database CHECK constraint holds this table to
             *     (2026_09_10_000008): lowercase, dotted, at most 100 characters.
             */
            name: string;
        };
        /** SyncSubscriptionsRequest */
        SyncSubscriptionsRequest: {
            event_types: string[];
        };
        /** TestEventResource */
        TestEventResource: {
            message: {
                id: string;
                event_type: string;
                source: string;
                created_at: string;
            };
            delivery_id: string;
            delivery_status: string;
        };
        /** UpdateApplicationRequest */
        UpdateApplicationRequest: {
            name: string;
        };
        /** UpdateEndpointRequest */
        UpdateEndpointRequest: {
            /**
             * @description Every field is a partial update: an operator flipping the
             *     status switch should not have to resend the name and URL too.
             */
            name?: string;
            /** Format: uri */
            url?: string;
            /**
             * @description A plain 'in:' list rather than Rule::enum(): that helper
             *     implements the older Rule contract, not ValidationRule, so it
             *     does not fit the one shape every rule in this class carries.
             * @enum {string}
             */
            status?: "enabled" | "disabled";
        };
    };
    responses: {
        /** @description Authorization error */
        AuthorizationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "csrf-cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "api-keys.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `ApiKeyResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ApiKeyResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "api-keys.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreApiKeyRequest"];
            };
        };
        responses: {
            /** @description `IssuedApiKeyResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedApiKeyResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "api-keys.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The api key public id */
                apiKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "applications.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `ApplicationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ApplicationResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "applications.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreApplicationRequest"];
            };
        };
        responses: {
            /** @description `ApplicationResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "applications.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The application public id */
                application: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ApplicationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "applications.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The application public id */
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationRequest"];
            };
        };
        responses: {
            /** @description `ApplicationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "applications.endpoints.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The application public id */
                application: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `EndpointResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EndpointResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "applications.endpoints.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The application public id */
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreEndpointRequest"];
            };
        };
        responses: {
            /** @description `EndpointResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "endpoints.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The endpoint public id */
                endpoint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `EndpointResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "endpoints.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The endpoint public id */
                endpoint: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateEndpointRequest"];
            };
        };
        responses: {
            /** @description `EndpointResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "endpoints.subscriptions.sync": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The endpoint public id */
                endpoint: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncSubscriptionsRequest"];
            };
        };
        responses: {
            /** @description `EndpointResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "endpoints.test-events.store": {
        parameters: {
            query?: never;
            header?: {
                /** @description An optional key scoped to this tenant. Replaying it with an identical body returns the original result unchanged (200, Idempotent-Replay: true); a different body answers 409. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description The endpoint public id */
                endpoint: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendTestEventRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay: an identical earlier request already produced this result. */
            200: {
                headers: {
                    /** @description Present, and always "true", only on the replayed response. */
                    "Idempotent-Replay"?: "true";
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestEventResource"];
                };
            };
            /** @description Accepted: this request produced a new record. */
            201: {
                headers: {
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestEventResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description This tenant's quota for the current billing period has been exhausted. */
            402: {
                headers: {
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            /** @description This Idempotency-Key was already used for a request with a different body. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            /** @description The rate limit for this tenant has been exceeded. */
            429: {
                headers: {
                    /** @description Seconds until the bucket next refills. */
                    "Retry-After"?: number;
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    "endpoints.secrets.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The endpoint public id */
                endpoint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `EndpointSecretResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EndpointSecretResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "endpoints.secrets.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The endpoint public id */
                endpoint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `IssuedEndpointSecretResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedEndpointSecretResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "endpoints.secrets.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The endpoint public id */
                endpoint: string;
                /** @description The secret public id */
                secret: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "event-types.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `EventTypeResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EventTypeResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "event-types.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreEventTypeRequest"];
            };
        };
        responses: {
            /** @description `EventTypeResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every dependency probe succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok" | "degraded";
                        /** Format: date-time */
                        checked_at: string;
                        duration_ms: number;
                        checks: {
                            /** @description database, redis, queue or migrations. */
                            name: string;
                            /** @enum {string} */
                            status: "ok" | "degraded";
                            duration_ms: number;
                        }[];
                    };
                };
            };
            /** @description At least one dependency (database, Redis, the queue or pending migrations) failed its probe. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok" | "degraded";
                        /** Format: date-time */
                        checked_at: string;
                        duration_ms: number;
                        checks: {
                            /** @description database, redis, queue or migrations. */
                            name: string;
                            /** @enum {string} */
                            status: "ok" | "degraded";
                            duration_ms: number;
                        }[];
                    };
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `IdentityResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "messages.store": {
        parameters: {
            query?: never;
            header?: {
                /** @description An optional key scoped to this tenant. Replaying it with an identical body returns the original result unchanged (200, Idempotent-Replay: true); a different body answers 409. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description The application public id */
                application: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishMessageRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay: an identical earlier request already produced this result. */
            200: {
                headers: {
                    /** @description Present, and always "true", only on the replayed response. */
                    "Idempotent-Replay"?: "true";
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResource"];
                };
            };
            /** @description Accepted: this request produced a new record. */
            201: {
                headers: {
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResource"];
                };
            };
            /** @description This tenant's quota for the current billing period has been exhausted. */
            402: {
                headers: {
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            /** @description This Idempotency-Key was already used for a request with a different body. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            /** @description The rate limit for this tenant has been exceeded. */
            429: {
                headers: {
                    /** @description Seconds until the bucket next refills. */
                    "Retry-After"?: number;
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    "replays.message": {
        parameters: {
            query?: never;
            header?: {
                /** @description An optional key scoped to this tenant. Replaying it with an identical body returns the original result unchanged (200, Idempotent-Replay: true); a different body answers 409. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description The message public id */
                message: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReplayMessageRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay: an identical earlier request already produced this result. */
            200: {
                headers: {
                    /** @description Present, and always "true", only on the replayed response. */
                    "Idempotent-Replay"?: "true";
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResource"];
                };
            };
            /** @description Accepted: this request produced a new record. */
            201: {
                headers: {
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description This tenant's quota for the current billing period has been exhausted. */
            402: {
                headers: {
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            /** @description No original delivery exists for this message and endpoint. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description This Idempotency-Key was already used for a request with a different body. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            /** @description The rate limit for this tenant has been exceeded. */
            429: {
                headers: {
                    /** @description Seconds until the bucket next refills. */
                    "Retry-After"?: number;
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    "replays.range": {
        parameters: {
            query?: never;
            header?: {
                /** @description An optional key scoped to this tenant. Replaying it with an identical body returns the original result unchanged (200, Idempotent-Replay: true); a different body answers 409. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description The endpoint public id */
                endpoint: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayRangeRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay: an identical earlier request already produced this result. */
            200: {
                headers: {
                    /** @description Present, and always "true", only on the replayed response. */
                    "Idempotent-Replay"?: "true";
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResource"];
                };
            };
            /** @description Accepted: this request produced a new record. */
            201: {
                headers: {
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResource"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description This tenant's quota for the current billing period has been exhausted. */
            402: {
                headers: {
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            403: components["responses"]["AuthorizationException"];
            /** @description No original delivery exists for this message and endpoint. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            /** @description This Idempotency-Key was already used for a request with a different body. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            /** @description The rate limit for this tenant has been exceeded. */
            429: {
                headers: {
                    /** @description Seconds until the bucket next refills. */
                    "Retry-After"?: number;
                    /** @description The token bucket capacity for this tenant. */
                    "RateLimit-Limit"?: number;
                    /** @description Tokens left in the current bucket. */
                    "RateLimit-Remaining"?: number;
                    /** @description Seconds until the bucket next refills. */
                    "RateLimit-Reset"?: number;
                    /** @description The cumulative quota for the current billing period. */
                    "Quota-Limit"?: number;
                    /** @description Quota left in the current billing period. */
                    "Quota-Remaining"?: number;
                    /** @description Seconds until the current billing period resets. */
                    "Quota-Reset"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description `IdentityResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityResource"];
                };
            };
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
}
