<?php

declare(strict_types=1);

use App\Support\Database\MonthlyPartitions;
use App\Support\Tenancy\RowLevelSecurity;
use Carbon\CarbonImmutable;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/*
 * Every HTTP attempt at every delivery, kept exactly as it happened. It is
 * partitioned by month for the same reason messages is: this is the other table
 * a working delivery engine writes to constantly.
 *
 * delivery_id and endpoint_id carry no foreign key, for the same reason
 * deliveries.message_id does not: the table is partitioned, and a partitioned
 * table has no plain single-column key for a constraint to reference.
 * endpoint_id is carried here at all — rather than reached through delivery_id —
 * because it is what the circuit breaker's rolling-window read (Step 8) filters
 * on, on every attempt, and that read should not need a join to do it.
 *
 * There is no updated_at: nothing in the application ever asks to change an
 * attempt once it is recorded, so the column recording that change does not
 * exist either.
 */
return new class extends Migration
{
    public function up(): void
    {
        $columns = [
            'id bigint GENERATED BY DEFAULT AS IDENTITY',
            'public_id varchar(40) NOT NULL',
            'tenant_id bigint NOT NULL REFERENCES tenants (id) ON DELETE CASCADE',
            'delivery_id bigint NOT NULL',
            'endpoint_id bigint NOT NULL',
            'attempt_number integer NOT NULL',
            'outcome varchar(20) NOT NULL',
            'request_headers jsonb NOT NULL',
            'request_body text NOT NULL',
            'response_status smallint NULL',
            'response_headers jsonb NULL',
            'response_body text NULL',
            'error_message text NULL',
            'duration_ms integer NOT NULL',
            'created_at timestamp(0) without time zone NOT NULL',
            'PRIMARY KEY (id, created_at)',
            'UNIQUE (public_id, created_at)',
            'CONSTRAINT delivery_attempts_attempt_number_check CHECK (attempt_number >= 1)',
            'CONSTRAINT delivery_attempts_duration_check CHECK (duration_ms >= 0)',
            // 256 KiB — the same ceiling messages.payload holds itself to.
            'CONSTRAINT delivery_attempts_request_body_size_check '.
                'CHECK (octet_length(request_body) <= 262144)',
            'CONSTRAINT delivery_attempts_response_body_size_check '.
                'CHECK (response_body IS NULL OR octet_length(response_body) <= 262144)',
            'CONSTRAINT delivery_attempts_outcome_check CHECK (outcome IN '.
                "('succeeded', 'failed', 'timeout', 'dns_error', 'tls_error', 'connection_error'))",
            // A response status exists exactly when a response was actually
            // received, and "succeeded" means exactly a 2xx one — that
            // classification is what the outcome name already says, not a
            // second, driftable fact recorded beside it.
            'CONSTRAINT delivery_attempts_response_status_shape_check CHECK ('.
                "(outcome = 'succeeded' AND response_status BETWEEN 200 AND 299) OR ".
                '(outcome = \'failed\' AND response_status BETWEEN 100 AND 599 '.
                'AND response_status NOT BETWEEN 200 AND 299) OR '.
                "(outcome IN ('timeout', 'dns_error', 'tls_error', 'connection_error') ".
                'AND response_status IS NULL))',
        ];

        DB::statement(
            'CREATE TABLE delivery_attempts ('.implode(', ', $columns).') PARTITION BY RANGE (created_at)'
        );

        // The retry timeline (Step 14): a delivery's attempts, in order.
        DB::statement(
            'CREATE INDEX delivery_attempts_delivery_created_at_index '.
            'ON delivery_attempts (delivery_id, created_at)'
        );

        // The circuit breaker's rolling window (Step 8): an endpoint's recent
        // attempts.
        DB::statement(
            'CREATE INDEX delivery_attempts_endpoint_created_at_index '.
            'ON delivery_attempts (endpoint_id, created_at)'
        );

        RowLevelSecurity::protect('delivery_attempts');

        MonthlyPartitions::ensure('delivery_attempts', CarbonImmutable::now(), 2);
    }

    public function down(): void
    {
        Schema::dropIfExists('delivery_attempts');
    }
};
