<?php

declare(strict_types=1);

use App\Support\Database\MonthlyPartitions;
use App\Support\Tenancy\RowLevelSecurity;
use Carbon\CarbonImmutable;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/*
 * The message log: every event a tenant has published. It is the busiest table
 * in the system, so it is range-partitioned by month from the day it is created
 * rather than retrofitted once it is large.
 *
 * Partitioning is why this migration is raw SQL rather than a Blueprint —
 * Laravel's schema builder has no notion of PARTITION BY. It is also why the
 * primary key is (id, created_at) rather than id alone, and why the public
 * identifier is unique per (public_id, created_at) rather than globally: every
 * unique index on a partitioned table must include the partition key. public_id
 * stays unique in practice because a ULID's entropy makes a collision
 * astronomically unlikely, not because one index spans every partition.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::statement(
            'CREATE TABLE messages ('.
            'id bigint GENERATED BY DEFAULT AS IDENTITY, '.
            'public_id varchar(40) NOT NULL, '.
            'tenant_id bigint NOT NULL REFERENCES tenants (id) ON DELETE CASCADE, '.
            'application_id bigint NOT NULL REFERENCES applications (id) ON DELETE CASCADE, '.
            'event_type_id bigint NOT NULL REFERENCES event_types (id) ON DELETE CASCADE, '.
            'payload jsonb NOT NULL, '.
            'created_at timestamp(0) without time zone NOT NULL, '.
            'updated_at timestamp(0) without time zone NULL, '.
            'PRIMARY KEY (id, created_at), '.
            'UNIQUE (public_id, created_at), '.
            // 256 KiB. Step 4's ingest endpoint rejects an oversized payload
            // before it reaches this far; this is the backstop in the one place
            // every write to this table must pass through. Step 4 reads the same
            // figure from configuration and a test there holds the two equal.
            'CONSTRAINT messages_payload_size_check CHECK (octet_length(payload::text) <= 262144)'.
            ') PARTITION BY RANGE (created_at)'
        );

        // Serves an application's messages, newest first — the list Step 14
        // reads, scoped by the tenant predicate Row Level Security adds.
        DB::statement(
            'CREATE INDEX messages_tenant_application_created_at_index '.
            'ON messages (tenant_id, application_id, created_at)'
        );

        RowLevelSecurity::protect('messages');

        // The current month and a two-month runway, so the table can accept a
        // write the moment it exists. Keeping the horizon topped up from here is
        // the scheduled command's job, not this migration's.
        MonthlyPartitions::ensure('messages', CarbonImmutable::now(), 2);
    }

    public function down(): void
    {
        // Dropping a partitioned table drops every partition beneath it — the
        // indexes, the policy and the CHECK all go with it in one statement.
        Schema::dropIfExists('messages');
    }
};
